/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef finkel_TYPES_H
#define finkel_TYPES_H

#include <Thrift.h>
#include <TApplicationException.h>
#include <protocol/TProtocol.h>
#include <transport/TTransport.h>






class Bitmap {
 public:

  static const char* ascii_fingerprint; // = "99914B932BD37A50B983C5E7C90AE93B";
  static const uint8_t binary_fingerprint[16]; // = {0x99,0x91,0x4B,0x93,0x2B,0xD3,0x7A,0x50,0xB9,0x83,0xC5,0xE7,0xC9,0x0A,0xE9,0x3B};

  Bitmap() {
  }

  virtual ~Bitmap() throw() {}


  bool operator == (const Bitmap & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Bitmap &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Bitmap & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _KeyboardInput__isset {
  _KeyboardInput__isset() : text(false) {}
  bool text;
} _KeyboardInput__isset;

class KeyboardInput {
 public:

  static const char* ascii_fingerprint; // = "EFB929595D312AC8F305D5A794CFEDA1";
  static const uint8_t binary_fingerprint[16]; // = {0xEF,0xB9,0x29,0x59,0x5D,0x31,0x2A,0xC8,0xF3,0x05,0xD5,0xA7,0x94,0xCF,0xED,0xA1};

  KeyboardInput() : text("") {
  }

  virtual ~KeyboardInput() throw() {}

  std::string text;

  _KeyboardInput__isset __isset;

  void __set_text(const std::string& val) {
    text = val;
  }

  bool operator == (const KeyboardInput & rhs) const
  {
    if (!(text == rhs.text))
      return false;
    return true;
  }
  bool operator != (const KeyboardInput &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const KeyboardInput & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MouseInput__isset {
  _MouseInput__isset() : x(false), y(false), doubleClick(false) {}
  bool x;
  bool y;
  bool doubleClick;
} _MouseInput__isset;

class MouseInput {
 public:

  static const char* ascii_fingerprint; // = "E0991C843E3F9D01A30FF59D9FBC2CAF";
  static const uint8_t binary_fingerprint[16]; // = {0xE0,0x99,0x1C,0x84,0x3E,0x3F,0x9D,0x01,0xA3,0x0F,0xF5,0x9D,0x9F,0xBC,0x2C,0xAF};

  MouseInput() : x(0), y(0), doubleClick(0) {
  }

  virtual ~MouseInput() throw() {}

  int32_t x;
  int32_t y;
  bool doubleClick;

  _MouseInput__isset __isset;

  void __set_x(const int32_t val) {
    x = val;
  }

  void __set_y(const int32_t val) {
    y = val;
  }

  void __set_doubleClick(const bool val) {
    doubleClick = val;
  }

  bool operator == (const MouseInput & rhs) const
  {
    if (!(x == rhs.x))
      return false;
    if (!(y == rhs.y))
      return false;
    if (!(doubleClick == rhs.doubleClick))
      return false;
    return true;
  }
  bool operator != (const MouseInput &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MouseInput & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _UserInput__isset {
  _UserInput__isset() : keyboardInput(false), mouseInput(false) {}
  bool keyboardInput;
  bool mouseInput;
} _UserInput__isset;

class UserInput {
 public:

  static const char* ascii_fingerprint; // = "EA7B0BE456E446118AF5D50F744C8B81";
  static const uint8_t binary_fingerprint[16]; // = {0xEA,0x7B,0x0B,0xE4,0x56,0xE4,0x46,0x11,0x8A,0xF5,0xD5,0x0F,0x74,0x4C,0x8B,0x81};

  UserInput() {
  }

  virtual ~UserInput() throw() {}

  KeyboardInput keyboardInput;
  MouseInput mouseInput;

  _UserInput__isset __isset;

  void __set_keyboardInput(const KeyboardInput& val) {
    keyboardInput = val;
  }

  void __set_mouseInput(const MouseInput& val) {
    mouseInput = val;
  }

  bool operator == (const UserInput & rhs) const
  {
    if (!(keyboardInput == rhs.keyboardInput))
      return false;
    if (!(mouseInput == rhs.mouseInput))
      return false;
    return true;
  }
  bool operator != (const UserInput &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const UserInput & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};



#endif
