/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "finkel_constants.h"



const finkelConstants g_finkel_constants;

finkelConstants::finkelConstants() {
}



