/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef finkel_CONSTANTS_H
#define finkel_CONSTANTS_H

#include "finkel_types.h"



class finkelConstants {
 public:
  finkelConstants();

};

extern const finkelConstants g_finkel_constants;



#endif
